image: atlassian/default-image:latest

pipelines:
  branches:
    release/test_deploy:
      - step:
          caches:
            - composer
          script:
            - pipe: atlassian/rsync-deploy:0.3.1
              variables:
                USER: $SSH_USER
                SERVER: $SSH_HOST
                REMOTE_PATH: 'gruneasia2.info/public_html/spa-starter-vue2'
                LOCAL_PATH: '.'
                EXTRA_ARGS: '-p udw30cfw --exclude-from=deployment-exclude-list.txt'
                DEBUG: 'true'
                SSH_PORT: $SSH_PORT
      - step:
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SSH_KEY: $MY_SSH_KEY
                SERVER: $SSH_HOST
                COMMAND: 'cd gruneasia2.info/public_html/spa-starter-vue2 && npm install && npm run dev'
                PORT: $SSH_PORT