
version: "3"
services:
  nginx:
    image: nginx:1.17
    container_name: spa_nginx
    depends_on:
      - php-fpm
      - php-fpm-test
    ports:
      - 80:80
      # - 443:443
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../../nginx/default.ec2_ssl.conf:/etc/nginx/conf.d/default.conf:cached
      - ../../nginx/nginx_logs/:/var/log/nginx:delegated
      - ../../../client/:/usr/share/nginx/spa_project/client:cached
      - ../../../client_test/:/usr/share/nginx/spa_project/client_test:cached
      - ../../../api/:/usr/share/nginx/spa_project/api:cached
      - ../../../api_test/:/usr/share/nginx/spa_project/api_test:cached
  php-fpm:
    build: ../../php-fpm
    container_name: spa_php-fpm
    volumes:
      - ../../../api/:/var/www/html/spa_project/api:cached
      - ../../php-fpm/php.ini:/usr/local/etc/php/php.ini:cached
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    container_name: spa_phpmyadmin
    ports:
      - 8087:80
    volumes:
      - "../../phpmyadmin/sessions:/sessions"

  php-fpm-test:
    build: ../../php-fpm
    container_name: spa_test_php-fpm
    volumes:
      - ../../../api/:/var/www/html/spa_project/api_test:cached
      - ../../php-fpm/php.ini:/usr/local/etc/php/php.ini:cached